### ISSUE TITLE
Cannot read properties of undefined (reading 'slice')

### ISSUE THREAD

**Issue by KaneFreeman** [StaticJsCMS/static-cms-proxy-server#42]

**Comment by antonioalmeida** [comment]
Does this have to do with the setups where the entries are directories, e.g., `content/post-name/index.md` instead of files?

I get "No Entries" in the UI even though creating a new entry works succesfully. 

Basically with this setup: https://www.staticcms.org/docs/collection-types#media-and-public-folder

**Comment by KaneFreeman** [comment]
This issue was resolves in 3.0.1. I forgot to close this. Please open another issue for your problem with your config file provided.
